// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.6.1
// source: idl/converter.proto

package converter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	IsBin     bool   `protobuf:"varint,2,opt,name=isBin,proto3" json:"isBin,omitempty"`
	File      []byte `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	NeedDraco bool   `protobuf:"varint,4,opt,name=needDraco,proto3" json:"needDraco,omitempty"`
	NoZip     bool   `protobuf:"varint,5,opt,name=noZip,proto3" json:"noZip,omitempty"`
}

func (x *ConvertReq) Reset() {
	*x = ConvertReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_converter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertReq) ProtoMessage() {}

func (x *ConvertReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_converter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertReq.ProtoReflect.Descriptor instead.
func (*ConvertReq) Descriptor() ([]byte, []int) {
	return file_idl_converter_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConvertReq) GetIsBin() bool {
	if x != nil {
		return x.IsBin
	}
	return false
}

func (x *ConvertReq) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ConvertReq) GetNeedDraco() bool {
	if x != nil {
		return x.NeedDraco
	}
	return false
}

func (x *ConvertReq) GetNoZip() bool {
	if x != nil {
		return x.NoZip
	}
	return false
}

type ConvertResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []byte `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *ConvertResp) Reset() {
	*x = ConvertResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_converter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResp) ProtoMessage() {}

func (x *ConvertResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_converter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResp.ProtoReflect.Descriptor instead.
func (*ConvertResp) Descriptor() ([]byte, []int) {
	return file_idl_converter_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertResp) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

var File_idl_converter_proto protoreflect.FileDescriptor

var file_idl_converter_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x64, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x42, 0x69, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x42, 0x69, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x44, 0x72, 0x61, 0x63, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6e, 0x65, 0x65, 0x64, 0x44, 0x72, 0x61, 0x63, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x5a, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x6e, 0x6f, 0x5a, 0x69, 0x70, 0x22, 0x21, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x32, 0x39, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x54, 0x6f, 0x47, 0x6c, 0x74, 0x66, 0x12, 0x0b, 0x2e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x2f,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_idl_converter_proto_rawDescOnce sync.Once
	file_idl_converter_proto_rawDescData = file_idl_converter_proto_rawDesc
)

func file_idl_converter_proto_rawDescGZIP() []byte {
	file_idl_converter_proto_rawDescOnce.Do(func() {
		file_idl_converter_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_converter_proto_rawDescData)
	})
	return file_idl_converter_proto_rawDescData
}

var file_idl_converter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idl_converter_proto_goTypes = []interface{}{
	(*ConvertReq)(nil),  // 0: convertReq
	(*ConvertResp)(nil), // 1: convertResp
}
var file_idl_converter_proto_depIdxs = []int32{
	0, // 0: Converter.convertToGltf:input_type -> convertReq
	1, // 1: Converter.convertToGltf:output_type -> convertResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_converter_proto_init() }
func file_idl_converter_proto_init() {
	if File_idl_converter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_converter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_converter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_converter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_converter_proto_goTypes,
		DependencyIndexes: file_idl_converter_proto_depIdxs,
		MessageInfos:      file_idl_converter_proto_msgTypes,
	}.Build()
	File_idl_converter_proto = out.File
	file_idl_converter_proto_rawDesc = nil
	file_idl_converter_proto_goTypes = nil
	file_idl_converter_proto_depIdxs = nil
}
