// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.6.1
// source: idl/artifact_svr.proto

package artifact_svr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_STL  FileType = 0
	FileType_IGES FileType = 1
	FileType_STP  FileType = 2
	FileType_OBJ  FileType = 3
	FileType_FBX  FileType = 4
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "STL",
		1: "IGES",
		2: "STP",
		3: "OBJ",
		4: "FBX",
	}
	FileType_value = map[string]int32{
		"STL":  0,
		"IGES": 1,
		"STP":  2,
		"OBJ":  3,
		"FBX":  4,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_idl_artifact_svr_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_idl_artifact_svr_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_idl_artifact_svr_proto_rawDescGZIP(), []int{0}
}

type BaseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code    int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_artifact_svr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_artifact_svr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_idl_artifact_svr_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ArtifactInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location    string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *ArtifactInfo) Reset() {
	*x = ArtifactInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_artifact_svr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactInfo) ProtoMessage() {}

func (x *ArtifactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_idl_artifact_svr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactInfo.ProtoReflect.Descriptor instead.
func (*ArtifactInfo) Descriptor() ([]byte, []int) {
	return file_idl_artifact_svr_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArtifactInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type StoreArtifactReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []byte        `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Type FileType      `protobuf:"varint,2,opt,name=type,proto3,enum=FileType" json:"type,omitempty"`
	Info *ArtifactInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *StoreArtifactReq) Reset() {
	*x = StoreArtifactReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_artifact_svr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreArtifactReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreArtifactReq) ProtoMessage() {}

func (x *StoreArtifactReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_artifact_svr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreArtifactReq.ProtoReflect.Descriptor instead.
func (*StoreArtifactReq) Descriptor() ([]byte, []int) {
	return file_idl_artifact_svr_proto_rawDescGZIP(), []int{2}
}

func (x *StoreArtifactReq) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *StoreArtifactReq) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_STL
}

func (x *StoreArtifactReq) GetInfo() *ArtifactInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type StoreArtifactResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp   *BaseResp `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	ArtifactId string    `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
}

func (x *StoreArtifactResp) Reset() {
	*x = StoreArtifactResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_artifact_svr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreArtifactResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreArtifactResp) ProtoMessage() {}

func (x *StoreArtifactResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_artifact_svr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreArtifactResp.ProtoReflect.Descriptor instead.
func (*StoreArtifactResp) Descriptor() ([]byte, []int) {
	return file_idl_artifact_svr_proto_rawDescGZIP(), []int{3}
}

func (x *StoreArtifactResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *StoreArtifactResp) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type UpdateArtifactReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtifactId string        `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Info       *ArtifactInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *UpdateArtifactReq) Reset() {
	*x = UpdateArtifactReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_artifact_svr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtifactReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtifactReq) ProtoMessage() {}

func (x *UpdateArtifactReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_artifact_svr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtifactReq.ProtoReflect.Descriptor instead.
func (*UpdateArtifactReq) Descriptor() ([]byte, []int) {
	return file_idl_artifact_svr_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateArtifactReq) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *UpdateArtifactReq) GetInfo() *ArtifactInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type UpdateArtifactResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp *BaseResp `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
}

func (x *UpdateArtifactResp) Reset() {
	*x = UpdateArtifactResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_artifact_svr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtifactResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtifactResp) ProtoMessage() {}

func (x *UpdateArtifactResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_artifact_svr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtifactResp.ProtoReflect.Descriptor instead.
func (*UpdateArtifactResp) Descriptor() ([]byte, []int) {
	return file_idl_artifact_svr_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateArtifactResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type QueryArtifactReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtifactId            string `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	NeedBasicInfo         bool   `protobuf:"varint,2,opt,name=need_basic_info,json=needBasicInfo,proto3" json:"need_basic_info,omitempty"`
	NeedCompressed_3DFile bool   `protobuf:"varint,3,opt,name=need_compressed_3d_file,json=needCompressed3dFile,proto3" json:"need_compressed_3d_file,omitempty"`
	NeedSource_3DFile     bool   `protobuf:"varint,4,opt,name=need_source_3d_file,json=needSource3dFile,proto3" json:"need_source_3d_file,omitempty"`
}

func (x *QueryArtifactReq) Reset() {
	*x = QueryArtifactReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_artifact_svr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryArtifactReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArtifactReq) ProtoMessage() {}

func (x *QueryArtifactReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_artifact_svr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArtifactReq.ProtoReflect.Descriptor instead.
func (*QueryArtifactReq) Descriptor() ([]byte, []int) {
	return file_idl_artifact_svr_proto_rawDescGZIP(), []int{6}
}

func (x *QueryArtifactReq) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *QueryArtifactReq) GetNeedBasicInfo() bool {
	if x != nil {
		return x.NeedBasicInfo
	}
	return false
}

func (x *QueryArtifactReq) GetNeedCompressed_3DFile() bool {
	if x != nil {
		return x.NeedCompressed_3DFile
	}
	return false
}

func (x *QueryArtifactReq) GetNeedSource_3DFile() bool {
	if x != nil {
		return x.NeedSource_3DFile
	}
	return false
}

type QueryArtifactResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseResp          *BaseResp     `protobuf:"bytes,1,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	BasicInfo         *ArtifactInfo `protobuf:"bytes,2,opt,name=basic_info,json=basicInfo,proto3" json:"basic_info,omitempty"`
	Compressed_3DFile []byte        `protobuf:"bytes,3,opt,name=compressed_3d_file,json=compressed3dFile,proto3" json:"compressed_3d_file,omitempty"`
	Source_3DFile     []byte        `protobuf:"bytes,4,opt,name=source_3d_file,json=source3dFile,proto3" json:"source_3d_file,omitempty"`
}

func (x *QueryArtifactResp) Reset() {
	*x = QueryArtifactResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_artifact_svr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryArtifactResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArtifactResp) ProtoMessage() {}

func (x *QueryArtifactResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_artifact_svr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArtifactResp.ProtoReflect.Descriptor instead.
func (*QueryArtifactResp) Descriptor() ([]byte, []int) {
	return file_idl_artifact_svr_proto_rawDescGZIP(), []int{7}
}

func (x *QueryArtifactResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

func (x *QueryArtifactResp) GetBasicInfo() *ArtifactInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

func (x *QueryArtifactResp) GetCompressed_3DFile() []byte {
	if x != nil {
		return x.Compressed_3DFile
	}
	return nil
}

func (x *QueryArtifactResp) GetSource_3DFile() []byte {
	if x != nil {
		return x.Source_3DFile
	}
	return nil
}

var File_idl_artifact_svr_proto protoreflect.FileDescriptor

var file_idl_artifact_svr_proto_rawDesc = []byte{
	0x0a, 0x16, 0x69, 0x64, 0x6c, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x73,
	0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x60, 0x0a, 0x0c, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x68, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x5c,
	0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x11,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x3c, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x09, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x22, 0xc1, 0x01, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x65,
	0x64, 0x5f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x6e, 0x65, 0x65, 0x64, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x35, 0x0a, 0x17, 0x6e, 0x65, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x64, 0x5f, 0x33, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x14, 0x6e, 0x65, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x64, 0x33, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x13, 0x6e, 0x65, 0x65, 0x64,
	0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x33, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x6e, 0x65, 0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x33, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x22, 0xbd, 0x01, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a,
	0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x64, 0x5f, 0x33, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x10, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65, 0x64, 0x33, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x33, 0x64, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x33, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x2a, 0x38, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x54, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x49, 0x47, 0x45, 0x53, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x54, 0x50, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x4f, 0x42, 0x4a, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x42, 0x58, 0x10,
	0x04, 0x32, 0xc2, 0x01, 0x0a, 0x0f, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x12, 0x11, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x3b, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63,
	0x74, 0x12, 0x12, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0d,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x12, 0x11, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67,
	0x65, 0x6e, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x5f, 0x73, 0x76, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_artifact_svr_proto_rawDescOnce sync.Once
	file_idl_artifact_svr_proto_rawDescData = file_idl_artifact_svr_proto_rawDesc
)

func file_idl_artifact_svr_proto_rawDescGZIP() []byte {
	file_idl_artifact_svr_proto_rawDescOnce.Do(func() {
		file_idl_artifact_svr_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_artifact_svr_proto_rawDescData)
	})
	return file_idl_artifact_svr_proto_rawDescData
}

var file_idl_artifact_svr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idl_artifact_svr_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_idl_artifact_svr_proto_goTypes = []interface{}{
	(FileType)(0),              // 0: FileType
	(*BaseResp)(nil),           // 1: BaseResp
	(*ArtifactInfo)(nil),       // 2: ArtifactInfo
	(*StoreArtifactReq)(nil),   // 3: StoreArtifactReq
	(*StoreArtifactResp)(nil),  // 4: StoreArtifactResp
	(*UpdateArtifactReq)(nil),  // 5: UpdateArtifactReq
	(*UpdateArtifactResp)(nil), // 6: UpdateArtifactResp
	(*QueryArtifactReq)(nil),   // 7: QueryArtifactReq
	(*QueryArtifactResp)(nil),  // 8: QueryArtifactResp
}
var file_idl_artifact_svr_proto_depIdxs = []int32{
	0,  // 0: StoreArtifactReq.type:type_name -> FileType
	2,  // 1: StoreArtifactReq.info:type_name -> ArtifactInfo
	1,  // 2: StoreArtifactResp.base_resp:type_name -> BaseResp
	2,  // 3: UpdateArtifactReq.info:type_name -> ArtifactInfo
	1,  // 4: UpdateArtifactResp.base_resp:type_name -> BaseResp
	1,  // 5: QueryArtifactResp.base_resp:type_name -> BaseResp
	2,  // 6: QueryArtifactResp.basic_info:type_name -> ArtifactInfo
	3,  // 7: ArtifactService.StoreArtifact:input_type -> StoreArtifactReq
	5,  // 8: ArtifactService.UpdateArtifact:input_type -> UpdateArtifactReq
	7,  // 9: ArtifactService.QueryArtifact:input_type -> QueryArtifactReq
	4,  // 10: ArtifactService.StoreArtifact:output_type -> StoreArtifactResp
	6,  // 11: ArtifactService.UpdateArtifact:output_type -> UpdateArtifactResp
	8,  // 12: ArtifactService.QueryArtifact:output_type -> QueryArtifactResp
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_idl_artifact_svr_proto_init() }
func file_idl_artifact_svr_proto_init() {
	if File_idl_artifact_svr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_artifact_svr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_artifact_svr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_artifact_svr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreArtifactReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_artifact_svr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreArtifactResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_artifact_svr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtifactReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_artifact_svr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtifactResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_artifact_svr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryArtifactReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_artifact_svr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryArtifactResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_artifact_svr_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_artifact_svr_proto_goTypes,
		DependencyIndexes: file_idl_artifact_svr_proto_depIdxs,
		EnumInfos:         file_idl_artifact_svr_proto_enumTypes,
		MessageInfos:      file_idl_artifact_svr_proto_msgTypes,
	}.Build()
	File_idl_artifact_svr_proto = out.File
	file_idl_artifact_svr_proto_rawDesc = nil
	file_idl_artifact_svr_proto_goTypes = nil
	file_idl_artifact_svr_proto_depIdxs = nil
}
